on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string
    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: false

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -a
  second:
    runs-on: ubuntu-latest
    steps:
      - name: Display username
        run: echo ${{ inputs.username }}
      - name: Display Access Token
        run: echo ${{ secrets.access-token }}